### ISSUE TITLE
Fix the bug.

### ISSUE THREAD

**Issue by abskrj** [abhishekraj272/Easy-Send-Email#11]
**Code is not running after commiting  changes.**

- Someone review this issue and get it sorted.

**Comment by darshildave** [comment]
I have created a PR https://github.com/abhishekraj272/Linux-Email-Automation/pull/14

**Comment by abskrj** [comment]
Ok checking

**Comment by abskrj** [comment]
There is an update in the version.
Bug has been fixed.
