### ISSUE TITLE
Add feature.

### ISSUE THREAD

**Issue by abskrj** [abhishekraj272/Easy-Send-Email#5]
## Add feature to send attachment through the shell.
Update the test.py file.

**Comment by iArazar** [comment]
Hey @abhishekraj272 
What kind of attachment should be added?

**Comment by abskrj** [comment]
Currently add the feature to send image files. Later on more features will be updated.

**Comment by xandmaga** [comment]
Hi @iArazar, are you going to work on this issue? If it is no the case i'd like to work on it.
Nervermind, there is already a pull request, #7,  to it.

**Comment by iArazar** [comment]
@xandmaga feel free ;)

**Comment by abskrj** [comment]
Done
